// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projekt.Data;

#nullable disable

namespace Projekt.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260614115614_AddedData")]
    partial class AddedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Projekt.Entity.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ClientId");

                    b.ToTable("Clients", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Projekt.Entity.Contract", b =>
                {
                    b.Property<int>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContractId"));

                    b.Property<int>("AdditionalSupportYears")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("SoftwareId")
                        .HasColumnType("int");

                    b.Property<int>("SoftwareVersionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ContractId");

                    b.HasIndex("ClientId");

                    b.HasIndex("SoftwareId");

                    b.HasIndex("SoftwareVersionId");

                    b.ToTable("Contracts", (string)null);

                    b.HasData(
                        new
                        {
                            ContractId = 1,
                            AdditionalSupportYears = 1,
                            ClientId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            SoftwareVersionId = 3,
                            StartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPrice = 8000m
                        },
                        new
                        {
                            ContractId = 2,
                            AdditionalSupportYears = 0,
                            ClientId = 3,
                            CreatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2024, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            SoftwareVersionId = 5,
                            StartDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPrice = 4000m
                        });
                });

            modelBuilder.Entity("Projekt.Entity.Discount", b =>
                {
                    b.Property<int>("DiscountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiscountId"));

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRepetitive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("DiscountId");

                    b.ToTable("Discounts", (string)null);

                    b.HasData(
                        new
                        {
                            DiscountId = 1,
                            DiscountPercent = 10m,
                            EndDate = new DateTime(2024, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRepetitive = true,
                            Name = "Black Friday Discount",
                            StartDate = new DateTime(2024, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DiscountId = 2,
                            DiscountPercent = 15m,
                            EndDate = new DateTime(2024, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRepetitive = true,
                            Name = "Summer Sale",
                            StartDate = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Projekt.Entity.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("PaymentId");

                    b.HasIndex("ClientId");

                    b.HasIndex("ContractId");

                    b.ToTable("Payments", (string)null);

                    b.HasData(
                        new
                        {
                            PaymentId = 1,
                            Amount = 4000m,
                            ClientId = 1,
                            ContractId = 1,
                            Date = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PaymentId = 2,
                            Amount = 4000m,
                            ClientId = 1,
                            ContractId = 1,
                            Date = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PaymentId = 3,
                            Amount = 4000m,
                            ClientId = 3,
                            ContractId = 2,
                            Date = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Projekt.Entity.Software", b =>
                {
                    b.Property<int>("SoftwareId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SoftwareId"));

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SoftwareTypeId")
                        .HasColumnType("int");

                    b.HasKey("SoftwareId");

                    b.HasIndex("ClientId");

                    b.HasIndex("SoftwareTypeId");

                    b.ToTable("Software", (string)null);

                    b.HasData(
                        new
                        {
                            SoftwareId = 1,
                            Name = "FinManager Pro",
                            SoftwareTypeId = 1
                        },
                        new
                        {
                            SoftwareId = 2,
                            Name = "EduLearn",
                            SoftwareTypeId = 2
                        });
                });

            modelBuilder.Entity("Projekt.Entity.SoftwareType", b =>
                {
                    b.Property<int>("SoftwareTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SoftwareTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SoftwareTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SoftwareTypes", (string)null);

                    b.HasData(
                        new
                        {
                            SoftwareTypeId = 1,
                            Name = "Finanse"
                        },
                        new
                        {
                            SoftwareTypeId = 2,
                            Name = "Edukacja"
                        });
                });

            modelBuilder.Entity("Projekt.Entity.SoftwareVersion", b =>
                {
                    b.Property<int>("SoftwareVersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SoftwareVersionId"));

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoftwareId")
                        .HasColumnType("int");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("YearlyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SoftwareVersionId");

                    b.HasIndex("SoftwareId");

                    b.ToTable("SoftwareVersions", (string)null);

                    b.HasData(
                        new
                        {
                            SoftwareVersionId = 1,
                            ReleaseDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoftwareId = 1,
                            Version = "1.0.0",
                            YearlyPrice = 5000m
                        },
                        new
                        {
                            SoftwareVersionId = 2,
                            ReleaseDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoftwareId = 1,
                            Version = "2.0.0",
                            YearlyPrice = 6000m
                        },
                        new
                        {
                            SoftwareVersionId = 3,
                            ReleaseDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoftwareId = 1,
                            Version = "3.0.0",
                            YearlyPrice = 7000m
                        },
                        new
                        {
                            SoftwareVersionId = 4,
                            ReleaseDate = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoftwareId = 2,
                            Version = "1.0.0",
                            YearlyPrice = 3000m
                        },
                        new
                        {
                            SoftwareVersionId = 5,
                            ReleaseDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoftwareId = 2,
                            Version = "2.0.0",
                            YearlyPrice = 4000m
                        });
                });

            modelBuilder.Entity("Projekt.Entity.Subscription", b =>
                {
                    b.Property<int>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubscriptionId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubscriptionOfferId")
                        .HasColumnType("int");

                    b.HasKey("SubscriptionId");

                    b.HasIndex("ClientId");

                    b.HasIndex("SubscriptionOfferId");

                    b.ToTable("Subscriptions", (string)null);

                    b.HasData(
                        new
                        {
                            SubscriptionId = 1,
                            ClientId = 2,
                            EndDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubscriptionOfferId = 3
                        },
                        new
                        {
                            SubscriptionId = 2,
                            ClientId = 4,
                            EndDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubscriptionOfferId = 2
                        });
                });

            modelBuilder.Entity("Projekt.Entity.SubscriptionOffer", b =>
                {
                    b.Property<int>("SubscriptionOfferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubscriptionOfferId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RenewalPeriod")
                        .HasColumnType("int");

                    b.Property<int>("SoftwareId")
                        .HasColumnType("int");

                    b.HasKey("SubscriptionOfferId");

                    b.HasIndex("SoftwareId");

                    b.ToTable("SubscriptionOffers", (string)null);

                    b.HasData(
                        new
                        {
                            SubscriptionOfferId = 1,
                            Name = "FinManager Monthly",
                            Price = 500m,
                            RenewalPeriod = 1,
                            SoftwareId = 1
                        },
                        new
                        {
                            SubscriptionOfferId = 2,
                            Name = "FinManager Yearly",
                            Price = 5000m,
                            RenewalPeriod = 12,
                            SoftwareId = 1
                        },
                        new
                        {
                            SubscriptionOfferId = 3,
                            Name = "EduLearn Monthly",
                            Price = 300m,
                            RenewalPeriod = 1,
                            SoftwareId = 2
                        },
                        new
                        {
                            SubscriptionOfferId = 4,
                            Name = "EduLearn Yearly",
                            Price = 3000m,
                            RenewalPeriod = 12,
                            SoftwareId = 2
                        });
                });

            modelBuilder.Entity("Projekt.Entity.SubscriptionPayment", b =>
                {
                    b.Property<int>("SubscriptionPaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubscriptionPaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int");

                    b.HasKey("SubscriptionPaymentId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("SubscriptionPayments", (string)null);

                    b.HasData(
                        new
                        {
                            SubscriptionPaymentId = 1,
                            Amount = 300m,
                            PaymentDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PeriodEndDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PeriodStartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubscriptionId = 1
                        },
                        new
                        {
                            SubscriptionPaymentId = 2,
                            Amount = 5000m,
                            PaymentDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PeriodEndDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PeriodStartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubscriptionId = 2
                        });
                });

            modelBuilder.Entity("SoftwareDiscounts", b =>
                {
                    b.Property<int>("DiscountId")
                        .HasColumnType("int");

                    b.Property<int>("SoftwareId")
                        .HasColumnType("int");

                    b.HasKey("DiscountId", "SoftwareId");

                    b.HasIndex("SoftwareId");

                    b.ToTable("SoftwareDiscounts", (string)null);

                    b.HasData(
                        new
                        {
                            DiscountId = 1,
                            SoftwareId = 1
                        },
                        new
                        {
                            DiscountId = 2,
                            SoftwareId = 2
                        });
                });

            modelBuilder.Entity("Projekt.Entity.ClientCompany", b =>
                {
                    b.HasBaseType("Projekt.Entity.Client");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KRS")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.HasIndex("KRS")
                        .IsUnique()
                        .HasFilter("[KRS] IS NOT NULL");

                    b.ToTable("ClientCompanies", (string)null);

                    b.HasData(
                        new
                        {
                            ClientId = 3,
                            Email = "kontakt@techcorp.pl",
                            PhoneNumber = "22-300-400-500",
                            Address = "ul. Przemysłowa 10, Warszawa",
                            CompanyName = "TechCorp Sp. z o.o.",
                            KRS = "0000123456"
                        },
                        new
                        {
                            ClientId = 4,
                            Email = "biuro@edusoft.pl",
                            PhoneNumber = "12-400-500-600",
                            Address = "ul. Akademicka 3, Kraków",
                            CompanyName = "EduSoft S.A.",
                            KRS = "0000654321"
                        });
                });

            modelBuilder.Entity("Projekt.Entity.ClientPerson", b =>
                {
                    b.HasBaseType("Projekt.Entity.Client");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pesel")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nchar(11)")
                        .IsFixedLength();

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("Pesel")
                        .IsUnique()
                        .HasFilter("[Pesel] IS NOT NULL");

                    b.ToTable("ClientPerson", (string)null);

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            Email = "jan.kowalski@email.com",
                            PhoneNumber = "500-100-200",
                            Name = "Jan",
                            Pesel = "90010112345",
                            Surname = "Kowalski"
                        },
                        new
                        {
                            ClientId = 2,
                            Email = "anna.nowak@email.com",
                            PhoneNumber = "600-200-300",
                            Name = "Anna",
                            Pesel = "85052267890",
                            Surname = "Nowak"
                        });
                });

            modelBuilder.Entity("Projekt.Entity.Contract", b =>
                {
                    b.HasOne("Projekt.Entity.Client", "Client")
                        .WithMany("Contracts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projekt.Entity.Software", null)
                        .WithMany("Contracts")
                        .HasForeignKey("SoftwareId");

                    b.HasOne("Projekt.Entity.SoftwareVersion", "SoftwareVersion")
                        .WithMany("Contracts")
                        .HasForeignKey("SoftwareVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("SoftwareVersion");
                });

            modelBuilder.Entity("Projekt.Entity.Payment", b =>
                {
                    b.HasOne("Projekt.Entity.Client", "Client")
                        .WithMany("Payments")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Projekt.Entity.Contract", "Contract")
                        .WithMany("Payments")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("Projekt.Entity.Software", b =>
                {
                    b.HasOne("Projekt.Entity.Client", null)
                        .WithMany("Software")
                        .HasForeignKey("ClientId");

                    b.HasOne("Projekt.Entity.SoftwareType", "SoftwareType")
                        .WithMany("Software")
                        .HasForeignKey("SoftwareTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SoftwareType");
                });

            modelBuilder.Entity("Projekt.Entity.SoftwareVersion", b =>
                {
                    b.HasOne("Projekt.Entity.Software", "Softwares")
                        .WithMany("SoftwareVersions")
                        .HasForeignKey("SoftwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Softwares");
                });

            modelBuilder.Entity("Projekt.Entity.Subscription", b =>
                {
                    b.HasOne("Projekt.Entity.Client", "Client")
                        .WithMany("Subscriptions")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Projekt.Entity.SubscriptionOffer", "SubscriptionOffer")
                        .WithMany("Subscriptions")
                        .HasForeignKey("SubscriptionOfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("SubscriptionOffer");
                });

            modelBuilder.Entity("Projekt.Entity.SubscriptionOffer", b =>
                {
                    b.HasOne("Projekt.Entity.Software", "Software")
                        .WithMany("SubscriptionOffers")
                        .HasForeignKey("SoftwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Software");
                });

            modelBuilder.Entity("Projekt.Entity.SubscriptionPayment", b =>
                {
                    b.HasOne("Projekt.Entity.Subscription", "Subscription")
                        .WithMany("SubscriptionPayments")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("SoftwareDiscounts", b =>
                {
                    b.HasOne("Projekt.Entity.Discount", null)
                        .WithMany()
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projekt.Entity.Software", null)
                        .WithMany()
                        .HasForeignKey("SoftwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Projekt.Entity.ClientCompany", b =>
                {
                    b.HasOne("Projekt.Entity.Client", null)
                        .WithOne()
                        .HasForeignKey("Projekt.Entity.ClientCompany", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Projekt.Entity.ClientPerson", b =>
                {
                    b.HasOne("Projekt.Entity.Client", null)
                        .WithOne()
                        .HasForeignKey("Projekt.Entity.ClientPerson", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Projekt.Entity.Client", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("Payments");

                    b.Navigation("Software");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Projekt.Entity.Contract", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Projekt.Entity.Software", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("SoftwareVersions");

                    b.Navigation("SubscriptionOffers");
                });

            modelBuilder.Entity("Projekt.Entity.SoftwareType", b =>
                {
                    b.Navigation("Software");
                });

            modelBuilder.Entity("Projekt.Entity.SoftwareVersion", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("Projekt.Entity.Subscription", b =>
                {
                    b.Navigation("SubscriptionPayments");
                });

            modelBuilder.Entity("Projekt.Entity.SubscriptionOffer", b =>
                {
                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
